services:
  docs:
    image: dance_forge_local_docs
    container_name: dance_forge_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./dance_forge:/app/dance_forge:z
    ports:
      - '9000:9000'
    command: /start-docs
